[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["zzwtsy <zzwtsy@yumdeb.top>"]

[dependencies]
anyhow = { workspace = true }
salvo = "0.71.1"
tracing = "0.1"
tracing-subscriber = "0.3"
common = { path = "../common" }